[package]
name = "pywinpty"
version = "0.1.0"
authors = ["Edgar Andrés Margffoy Tuay <andfoy@gmail.com>"]
description = "Pseudo terminal support for Windows from Python."
repository = "https://github.com/spyder-ide/pywinpty"
license = "MIT"
keywords = ["pty", "pseudo-terminal", "conpty", "windows", "winpty"]
readme = "README.md"
edition = "2018"
links = "winpty"

[lib]
name = "pywinpty_rs"
crate-type = ["cdylib"]

[dependencies]
libc = "0.2.81"
cxx = "1.0.45"

[dependencies.pyo3]
version = "0.13.2"
features = ["extension-module"]

[build-dependencies]
cxx-build = {version = "1.0.45", features = ["parallel"]}
pywinpty_findlib = { version = "=0.1.0", path = "findlib" }
which = "4.1.0"
