name: Windows tests

on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master
jobs:
    windows:
        name: Windows Py${{ matrix.PYTHON_VERSION }}
        runs-on: windows-latest
        env:
            PYTHON_VERSION: ${{ matrix.PYTHON_VERSION }}
            RUNNER_OS: "windows"
        strategy:
            fail-fast: false
            matrix:
                PYTHON_VERSION: ["3.6", "3.7", "3.8", "3.9"]
        steps:
            - name: Checkout branch
              uses: actions/checkout@v2
            - name: Install latest Rust stable
              uses: actions-rs/toolchain@v1
              with:
                toolchain: stable
                target: x86_64-pc-windows-msvc
                override: true
                components: rustfmt, clippy
            - name: Install miniconda
              uses: conda-incubator/setup-miniconda@v2
              with:
                auto-update-conda: true
                activate-environment: test
                channels: conda-forge,defaults
                python-version: ${{ matrix.PYTHON_VERSION }}
            - name: Conda env info
              shell: bash -l {0}
              run: conda env list
            - name: Install winpty
              shell: bash -l {0}
              run: conda install -y winpty
            - name: Install build/test dependencies
              shell: bash -l {0}
              run: pip install maturin toml pytest pytest-lazy-fixture flaky
            - name: Build pywinpty
              shell: bash -l {0}
              run: maturin develop
            - name: Run tests
              shell: bash -l {0}
              run: pytest -x -v -s winpty/tests
